title: ArÃªte
description: >-
  The world's fastest multiplatform game engine.
base_url: /arete

remote_theme: jekyll/minima

minima:
 skin: dark
 social_links:
  - { platform: discord, user_url: "https://discord.gg/hRQSxztaFP" }
  - { platform: twitter, user_url: "https://twitter.com/_jamesordner" }
  - { platform: linkedin, user_url: "https://www.linkedin.com/in/james-ordner-610570219" }

show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-remote-theme

permalink: /:categories/:slug/
